# Настройки приложения
replicaCount: 3

image:
  repository: devops-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000
  name: http

postgres:
  image: postgres:13
  storage: 1Gi
  database: devops_db
  user: devops_user
  password: devops_pass

monitoring:
  enabled: true
  podMonitor:
    interval: 30s
    path: /metrics
    port: http
